language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t irwing/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true irwing/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-614850410872"
  bucket_path: "docker-react"
  on:
   branch: main
  access_key_id: $AWS_ACCESS
  secret_access_key:
   secure: "$AWS_SECRET"