language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t irwing/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true irwing/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "$AWS_BEANSTALK_REGION"
  app: "$AWS_BEANSTALK_APP"
  env: "$AWS_BEANSTALK_ENV"
  bucket_name: "$AWS_BUCKET"
  bucket_path: "$AWS_BEANSTALK_APP"
  on:
   branch: main
  access_key_id: $AWS_ACCESS
  secret_access_key: "$AWS_SECRET"