FROM node:alpine

USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json yarn.lock ./

RUN yarn install

COPY --chown=node:node ./ ./

CMD ["yarn", "start"]